-- Sistema de Consulta Histórica y Gestión de Facturación GobreeBelt
-- Ejecutar en Supabase SQL editor o mediante Supabase CLI.

create extension if not exists pg_trgm;
create extension if not exists unaccent;

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  rfc varchar(20),
  direccion text,
  telefono varchar(60),
  email varchar(180),
  contacto_principal varchar(180),
  notas text,
  created_at timestamptz not null default now()
);

create table if not exists public.facturas (
  id uuid primary key default gen_random_uuid(),
  folio varchar(80) not null,
  fecha date not null,
  cliente_id uuid not null references public.clientes(id) on delete restrict,
  oc varchar(120),
  codigo_interno varchar(120),
  subtotal numeric(14,2),
  iva numeric(14,2),
  total numeric(14,2),
  observaciones text,
  estatus varchar(20) not null default 'Pendiente' check (estatus in ('Pendiente', 'Validada', 'Archivada')),
  pdf_url text,
  xml_url text,
  imagen_url text,
  fts tsvector generated always as (
    setweight(to_tsvector('spanish', coalesce(observaciones, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(folio, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(oc, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(codigo_interno, '')), 'B')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cliente_id, folio)
);

create table if not exists public.partidas (
  id uuid primary key default gen_random_uuid(),
  factura_id uuid not null references public.facturas(id) on delete cascade,
  descripcion text,
  tipo_banda varchar(180),
  ancho_mm numeric(12,2),
  longitud_mm numeric(12,2),
  medidas_internas varchar(180),
  guia varchar(180),
  tipo_union varchar(180),
  cantidad numeric(12,2) not null default 1,
  precio_unitario numeric(14,2),
  importe numeric(14,2),
  fts tsvector generated always as (
    setweight(to_tsvector('spanish', coalesce(descripcion, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(tipo_banda, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(medidas_internas, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(guia, '')), 'C')
  ) stored
);

create table if not exists public.documentos_factura (
  id uuid primary key default gen_random_uuid(),
  factura_id uuid not null references public.facturas(id) on delete cascade,
  tipo varchar(20) not null check (tipo in ('pdf', 'xml', 'imagen')),
  nombre_archivo text not null,
  bucket text not null,
  storage_path text not null,
  url text not null,
  usuario_carga text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  usuario text,
  rol varchar(40),
  accion varchar(80) not null,
  tabla varchar(80) not null,
  registro_id text,
  cambios jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_facturas_updated_at on public.facturas;
create trigger trg_facturas_updated_at before update on public.facturas
for each row execute function public.set_updated_at();

-- Índices de rendimiento para más de 50,000 registros.
create index if not exists idx_clientes_rfc on public.clientes (rfc);
create index if not exists idx_clientes_nombre_trgm on public.clientes using gin (nombre gin_trgm_ops);
create index if not exists idx_facturas_folio on public.facturas (folio);
create index if not exists idx_facturas_cliente_id on public.facturas (cliente_id);
create index if not exists idx_facturas_oc on public.facturas (oc);
create index if not exists idx_facturas_codigo_interno on public.facturas (codigo_interno);
create index if not exists idx_facturas_fecha on public.facturas (fecha desc);
create index if not exists idx_facturas_total on public.facturas (total);
create index if not exists idx_facturas_estatus on public.facturas (estatus);
create index if not exists idx_facturas_fts on public.facturas using gin (fts);
create index if not exists idx_partidas_factura_id on public.partidas (factura_id);
create index if not exists idx_partidas_ancho_mm on public.partidas (ancho_mm);
create index if not exists idx_partidas_longitud_mm on public.partidas (longitud_mm);
create index if not exists idx_partidas_medidas_internas on public.partidas (medidas_internas);
create index if not exists idx_partidas_tipo_banda on public.partidas (tipo_banda);
create index if not exists idx_partidas_guia on public.partidas (guia);
create index if not exists idx_partidas_fts on public.partidas using gin (fts);
create index if not exists idx_audit_logs_fecha on public.audit_logs (fecha desc);

-- Búsqueda global priorizando observaciones/descripción y cubriendo cliente/RFC/datos técnicos.
create or replace view public.v_facturas_busqueda as
select
  f.*,
  c.nombre as cliente_nombre,
  c.rfc,
  p.descripcion,
  p.tipo_banda,
  p.ancho_mm,
  p.longitud_mm,
  p.medidas_internas,
  p.guia,
  (
    setweight(to_tsvector('spanish', coalesce(f.observaciones, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(p.descripcion, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(c.nombre, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(c.rfc, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(f.folio, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(f.oc, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(f.codigo_interno, '')), 'B') ||
    setweight(to_tsvector('spanish', coalesce(p.tipo_banda, '')), 'C') ||
    setweight(to_tsvector('spanish', coalesce(p.medidas_internas, '')), 'C') ||
    setweight(to_tsvector('spanish', coalesce(p.guia, '')), 'C')
  ) as search_vector
from public.facturas f
join public.clientes c on c.id = f.cliente_id
left join public.partidas p on p.factura_id = f.id;


-- RPC usada por /api/facturas para que la búsqueda global y los filtros técnicos
-- se ejecuten en PostgreSQL con paginación antes de cargar el detalle anidado.
create or replace function public.buscar_facturas_ids(
  p_q text default null,
  p_cliente text default null,
  p_rfc text default null,
  p_folio text default null,
  p_oc text default null,
  p_codigo_interno text default null,
  p_fecha_inicial date default null,
  p_fecha_final date default null,
  p_ancho_mm numeric default null,
  p_longitud_mm numeric default null,
  p_medidas_internas text default null,
  p_tipo_banda text default null,
  p_guia text default null,
  p_observaciones text default null,
  p_monto_minimo numeric default null,
  p_monto_maximo numeric default null,
  p_estatus text default null,
  p_limit integer default 25,
  p_offset integer default 0
)
returns table(id uuid, fecha date, total_count bigint)
language sql
stable
as $$
with query_values as (
  select
    nullif(trim(p_q), '') as q,
    case when nullif(trim(p_q), '') is null then null else plainto_tsquery('spanish', nullif(trim(p_q), '')) end as tsq
), matched as (
  select f.id, f.fecha
  from public.facturas f
  join public.clientes c on c.id = f.cliente_id
  cross join query_values qv
  where
    (p_folio is null or f.folio ilike '%' || p_folio || '%') and
    (p_oc is null or f.oc ilike '%' || p_oc || '%') and
    (p_codigo_interno is null or f.codigo_interno ilike '%' || p_codigo_interno || '%') and
    (p_estatus is null or f.estatus ilike '%' || p_estatus || '%') and
    (p_cliente is null or c.nombre ilike '%' || p_cliente || '%' or c.rfc ilike '%' || p_cliente || '%') and
    (p_rfc is null or c.rfc ilike '%' || p_rfc || '%') and
    (p_fecha_inicial is null or f.fecha >= p_fecha_inicial) and
    (p_fecha_final is null or f.fecha <= p_fecha_final) and
    (p_monto_minimo is null or f.total >= p_monto_minimo) and
    (p_monto_maximo is null or f.total <= p_monto_maximo) and
    (p_observaciones is null or f.observaciones ilike '%' || p_observaciones || '%') and
    (
      qv.q is null or
      f.fts @@ qv.tsq or
      c.nombre ilike '%' || qv.q || '%' or
      c.rfc ilike '%' || qv.q || '%' or
      exists (select 1 from public.partidas p where p.factura_id = f.id and p.fts @@ qv.tsq) or
      exists (
        select 1 from public.partidas p
        where p.factura_id = f.id and (
          p.descripcion ilike '%' || qv.q || '%' or
          p.tipo_banda ilike '%' || qv.q || '%' or
          p.medidas_internas ilike '%' || qv.q || '%' or
          p.guia ilike '%' || qv.q || '%'
        )
      )
    ) and
    (p_ancho_mm is null or exists (select 1 from public.partidas p where p.factura_id = f.id and p.ancho_mm = p_ancho_mm)) and
    (p_longitud_mm is null or exists (select 1 from public.partidas p where p.factura_id = f.id and p.longitud_mm = p_longitud_mm)) and
    (p_medidas_internas is null or exists (select 1 from public.partidas p where p.factura_id = f.id and p.medidas_internas ilike '%' || p_medidas_internas || '%')) and
    (p_tipo_banda is null or exists (select 1 from public.partidas p where p.factura_id = f.id and p.tipo_banda ilike '%' || p_tipo_banda || '%')) and
    (p_guia is null or exists (select 1 from public.partidas p where p.factura_id = f.id and p.guia ilike '%' || p_guia || '%'))
), counted as (
  select count(*) as total_count from matched
)
select m.id, m.fecha, c.total_count
from matched m
cross join counted c
order by m.fecha desc, m.id desc
limit greatest(1, least(coalesce(p_limit, 25), 100))
offset greatest(0, coalesce(p_offset, 0));
$$;

create or replace view public.v_facturacion_dashboard as
select
  (select count(*) from public.facturas) as facturas_registradas,
  (select count(*) from public.clientes) as clientes_registrados,
  (select count(*) from public.facturas where date_part('year', fecha) = date_part('year', current_date)) as facturas_este_anio,
  (select coalesce(sum(total), 0) from public.facturas where date_part('year', fecha) = date_part('year', current_date)) as ventas_este_anio,
  (select count(*) from public.facturas where date_trunc('month', fecha) = date_trunc('month', current_date)) as facturas_este_mes,
  (select coalesce(sum(total), 0) from public.facturas where date_trunc('month', fecha) = date_trunc('month', current_date)) as ventas_este_mes;

create or replace view public.v_clientes_frecuentes as
select c.id, c.nombre, c.rfc, count(f.id) as facturas, coalesce(sum(f.total),0) as total_comprado
from public.clientes c join public.facturas f on f.cliente_id = c.id
group by c.id, c.nombre, c.rfc order by facturas desc, total_comprado desc;

create or replace view public.v_medidas_mas_vendidas as
select ancho_mm, longitud_mm, medidas_internas, count(*) as partidas, coalesce(sum(cantidad),0) as cantidad
from public.partidas group by ancho_mm, longitud_mm, medidas_internas order by partidas desc;

create or replace view public.v_bandas_mas_vendidas as
select tipo_banda, count(*) as partidas, coalesce(sum(cantidad),0) as cantidad, coalesce(sum(importe),0) as importe
from public.partidas where tipo_banda is not null and tipo_banda <> '' group by tipo_banda order by partidas desc;

create or replace view public.v_ventas_por_anio as
select date_part('year', fecha)::int as anio, count(*) as facturas, coalesce(sum(total),0) as total
from public.facturas group by anio order by anio desc;

create or replace view public.v_ventas_por_mes as
select to_char(date_trunc('month', fecha), 'YYYY-MM') as mes, count(*) as facturas, coalesce(sum(total),0) as total
from public.facturas group by mes order by mes desc;

create or replace view public.v_ventas_por_cliente as
select c.id, c.nombre, c.rfc, coalesce(sum(f.total),0) as total
from public.clientes c join public.facturas f on f.cliente_id = c.id group by c.id, c.nombre, c.rfc order by total desc;

create or replace view public.v_facturas_por_cliente as
select c.id, c.nombre, c.rfc, count(f.id) as facturas
from public.clientes c left join public.facturas f on f.cliente_id = c.id group by c.id, c.nombre, c.rfc order by facturas desc;

create or replace view public.v_facturas_por_usuario as
select usuario, count(*) filter (where accion in ('crear','importar_xml')) as facturas_capturadas
from public.audit_logs group by usuario order by facturas_capturadas desc;

-- RLS: las API serverless usan SERVICE_ROLE_KEY. Si se exponen claves anon, crear políticas específicas antes de habilitar escritura directa.
alter table public.clientes enable row level security;
alter table public.facturas enable row level security;
alter table public.partidas enable row level security;
alter table public.documentos_factura enable row level security;
alter table public.audit_logs enable row level security;

-- Buckets esperados en Supabase Storage: facturas-pdf, facturas-xml, facturas-imagenes.
insert into storage.buckets (id, name, public) values
  ('facturas-pdf', 'facturas-pdf', true),
  ('facturas-xml', 'facturas-xml', true),
  ('facturas-imagenes', 'facturas-imagenes', true)
on conflict (id) do nothing;
